### PR TITLE
Logo: nginx 20 years.

### PR DESCRIPTION
**Pull request by lcrilly**

### CODE REVIEW

**Review by pluknet — CHANGES_REQUESTED** [review]
.orig files needs to be removed

**Comment by lcrilly** [comment]
> What about preserving the original nginx.png file in order to reference it back later?

That logo was superseded by the "green hex" logo back in 2020 but was never updated here. We should revert to an undecorated version of this logo after the celebration period.

**Comment by pluknet** [comment]
>That logo was superseded

**Comment by pluknet** [comment]
>That logo was superseded ...
Ok, sounds reasonable.

**Comment by pluknet** [comment]
You should probably also update docker-nginx.conf for nginx.png

**Comment by pluknet** [comment]
Refreshed series: .orig removal, xslt update.

**Review by pluknet — APPROVED** [review]

**Pull request merged**
